openapi: 3.0.3
info:
  title: QA API
  description: Quality Assessment endpoints for ebook drafts
  version: 1.0.0

paths:
  /api/projects/{project_id}/qa/analyze:
    post:
      summary: Trigger QA analysis
      description: Starts async QA analysis and returns a job_id for polling
      operationId: analyzeQuality
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Analysis job started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalyzeResponse'
        '404':
          description: Project not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/projects/{project_id}/qa/status/{job_id}:
    get:
      summary: Get QA job status
      description: Returns the status of a QA analysis job
      operationId: getQAJobStatus
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
        - name: job_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Job status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QAJobStatusResponse'
        '404':
          description: Job not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/projects/{project_id}/qa/report:
    get:
      summary: Get QA report
      description: Returns the latest QA report for the project
      operationId: getQAReport
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: QA report
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QAReportResponse'
        '404':
          description: Project or report not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/projects/{project_id}/qa/improve:
    post:
      summary: Run editor improvement pass (P2)
      description: Rewrites draft to fix identified issues
      operationId: runImprovePass
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Improvement job started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImproveResponse'
        '400':
          description: No issues to fix or draft missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    AnalyzeResponse:
      type: object
      required: [data, error]
      properties:
        data:
          type: object
          required: [job_id]
          properties:
            job_id:
              type: string
              description: Job ID for polling status
          nullable: true
        error:
          $ref: '#/components/schemas/ErrorDetail'

    QAJobStatusResponse:
      type: object
      required: [data, error]
      properties:
        data:
          type: object
          required: [job_id, status]
          properties:
            job_id:
              type: string
            status:
              type: string
              enum: [pending, running, completed, failed]
            progress:
              type: integer
              minimum: 0
              maximum: 100
              description: Progress percentage (0-100)
            report:
              $ref: '#/components/schemas/QAReport'
              description: Present when status is completed
            error_message:
              type: string
              description: Present when status is failed
          nullable: true
        error:
          $ref: '#/components/schemas/ErrorDetail'

    QAReportResponse:
      type: object
      required: [data, error]
      properties:
        data:
          $ref: '#/components/schemas/QAReport'
          nullable: true
        error:
          $ref: '#/components/schemas/ErrorDetail'

    ImproveResponse:
      type: object
      required: [data, error]
      properties:
        data:
          type: object
          properties:
            job_id:
              type: string
          nullable: true
        error:
          $ref: '#/components/schemas/ErrorDetail'

    ErrorResponse:
      type: object
      required: [data, error]
      properties:
        data:
          nullable: true
        error:
          $ref: '#/components/schemas/ErrorDetail'

    ErrorDetail:
      type: object
      nullable: true
      properties:
        code:
          type: string
        message:
          type: string

    QAReport:
      type: object
      required: [id, project_id, draft_hash, overall_score, rubric_scores, issues, issue_counts, truncated, total_issue_count, generated_at, analysis_duration_ms, version]
      properties:
        id:
          type: string
        project_id:
          type: string
        draft_hash:
          type: string
        overall_score:
          type: integer
          minimum: 1
          maximum: 100
        rubric_scores:
          $ref: '#/components/schemas/RubricScores'
        issues:
          type: array
          maxItems: 300
          items:
            $ref: '#/components/schemas/QAIssue'
        issue_counts:
          $ref: '#/components/schemas/IssueCounts'
        truncated:
          type: boolean
          description: True if issues list was capped at max
        total_issue_count:
          type: integer
          minimum: 0
          description: Actual total count (may exceed issues array length)
        generated_at:
          type: string
          format: date-time
        analysis_duration_ms:
          type: integer
        version:
          type: string

    IssueCounts:
      type: object
      required: [critical, warning, info]
      properties:
        critical:
          type: integer
          minimum: 0
        warning:
          type: integer
          minimum: 0
        info:
          type: integer
          minimum: 0

    RubricScores:
      type: object
      required: [structure, clarity, faithfulness, repetition, completeness]
      properties:
        structure:
          type: integer
          minimum: 1
          maximum: 100
        clarity:
          type: integer
          minimum: 1
          maximum: 100
        faithfulness:
          type: integer
          minimum: 1
          maximum: 100
        repetition:
          type: integer
          minimum: 1
          maximum: 100
        completeness:
          type: integer
          minimum: 1
          maximum: 100

    QAIssue:
      type: object
      required: [id, severity, issue_type, message]
      properties:
        id:
          type: string
        severity:
          type: string
          enum: [critical, warning, info]
        issue_type:
          type: string
          enum: [repetition, structure, clarity, faithfulness, completeness]
        chapter_index:
          type: integer
          nullable: true
        heading:
          type: string
          nullable: true
        location:
          type: string
          nullable: true
        message:
          type: string
        suggestion:
          type: string
          nullable: true
        metadata:
          type: object
          nullable: true
